class DeathType
  MOD_UNKNOWN = 0
  MOD_SHOTGUN = 1
  MOD_GAUNTLET = 2
  MOD_MACHINEGUN = 3
  MOD_GRENADE = 4
  MOD_GRENADE_SPLASH = 5
  MOD_ROCKET = 6
  MOD_ROCKET_SPLASH = 7
  MOD_PLASMA = 8
  MOD_PLASMA_SPLASH = 9
  MOD_RAILGUN = 10
  MOD_LIGHTNING = 11
  MOD_BFG = 12
  MOD_BFG_SPLASH = 13
  MOD_WATER = 14
  MOD_SLIME = 15
  MOD_LAVA = 16
  MOD_CRUSH = 17
  MOD_TELEFRAG = 18
  MOD_FALLING = 19
  MOD_SUICIDE = 20
  MOD_TARGET_LASER = 21
  MOD_TRIGGER_HURT = 22

  # Missionpack
  MOD_NAIL = 23
  MOD_CHAINGUN = 24
  MOD_PROXIMITY_MINE = 25
  MOD_KAMIKAZE = 26
  MOD_JUICED = 27

  MOD_GRAPPLE = 28

  def self.names
    {
      MOD_UNKNOWN => 'MOD_UNKNOWN',
      MOD_SHOTGUN => 'MOD_SHOTGUN',
      MOD_GAUNTLET => 'MOD_GAUNTLET',
      MOD_MACHINEGUN => 'MOD_MACHINEGUN',
      MOD_GRENADE => 'MOD_GRENADE',
      MOD_GRENADE_SPLASH => 'MOD_GRENADE_SPLASH',
      MOD_ROCKET => 'MOD_ROCKET',
      MOD_ROCKET_SPLASH => 'MOD_ROCKET_SPLASH',
      MOD_PLASMA => 'MOD_PLASMA',
      MOD_PLASMA_SPLASH => 'MOD_PLASMA_SPLASH',
      MOD_RAILGUN => 'MOD_RAILGUN',
      MOD_LIGHTNING => 'MOD_LIGHTNING',
      MOD_BFG => 'MOD_BFG',
      MOD_BFG_SPLASH => 'MOD_BFG_SPLASH',
      MOD_WATER => 'MOD_WATER',
      MOD_SLIME => 'MOD_SLIME',
      MOD_LAVA => 'MOD_LAVA',
      MOD_CRUSH => 'MOD_CRUSH',
      MOD_TELEFRAG => 'MOD_TELEFRAG',
      MOD_FALLING => 'MOD_FALLING',
      MOD_SUICIDE => 'MOD_SUICIDE',
      MOD_TARGET_LASER => 'MOD_TARGET_LASER',
      MOD_TRIGGER_HURT => 'MOD_TRIGGER_HURT',
      MOD_NAIL => 'MOD_NAIL',
      MOD_CHAINGUN => 'MOD_CHAINGUN',
      MOD_PROXIMITY_MINE => 'MOD_PROXIMITY_MINE',
      MOD_KAMIKAZE => 'MOD_KAMIKAZE',
      MOD_JUICED => 'MOD_JUICED',
      MOD_GRAPPLE => 'MOD_GRAPPLE'
    }
  end
end
